### ISSUE TITLE
Is there no easy way of editing a template that saves forever?

### ISSUE THREAD

**Issue by CyberNeonHD** [potatoqualitee/discordrpc#7]
![afbeelding](https://user-images.githubusercontent.com/50114712/159651650-8369cccf-ee71-4475-ae7a-fc1e716457ca.png)
~~Going to the json files and adding the text doesn't work?~~ You need to fully close both explorer and Powershell

**Comment by CyberNeonHD** [comment]
Found this way to "edit" a template and "saving" it forever
![afbeelding](https://user-images.githubusercontent.com/50114712/159665354-7f4ca543-64f9-4819-bbb2-259f568fd237.png)

**Comment by potatoqualitee** [comment]
Thank you Cyber! That is a bummer that it doesn't re-fill it. Perhaps caching is too hard? When I get some time, ill try to see if this can be persisted.
